
# Methods
## Mark-recapture sampling

In 2023, FMCC and Harrison Lake collaboratively released X mussels (breakdown here) at X site. 
Of these X were individually tagged. 
In 2024, the site was sampled four times from June to October. 
*description of sampling here - see notes from Jess*. 
For each mussel encountered, we measured its overall length and recorded the tag number. 
Untagged mussels were not tagged. 
Were returned to stream, etc.

## POPAN description
We were interested primarily in estimating survival of the release cohort over time and the corresponding abundance on each occasion.
Thus, we analyzed these data using a POPAN mark-recapture framework, which allows for the estimation of both apparent surival and population size.
The POPAN model is a parameterization of the Jolly-Seber model *reference*. 
It models Jolly-Seber in terms of a super population (N) and probability of entry (see link below for Gary White overview and Schwarz and Arnason (1996) for original paper).
It has four model parameters:

1) Super population 
2) probability of entry into the super population 
3) apparent survival
4) capture probability

During field sampling, we only recorded already tagged individuals without tagging new mussels (specify that this because there really weren't new mussels yet?)
Consequently, we considered the super population to be the initial release cohort.
We also assumed that pent was 0. 
Neither of these two model parameters were estimated based on modeling. 

## Data Analysis
Data for the tagged individuals released in 2023 were combined with data from the four sampling occasions in 2024. 
We used the resulting data to construct an encounter history for each individually tagged mussel released in 2023. 
This encounter history describes whether a mussel was observed on an occasion when it was possible to be observed (i.e., the initial release or one of the four sampling occasions). 
A total of four species were released in 2023. 
The encounter histories for each species were analyzed separately using the computer program MARK and the R package RMARK. 
MARK is a program (White and Burnham 1999) that was developed for analyzing various types of mark-recapture datasets under a variety of frameworks (e.g., CJS, JS, POPAN, etc.).
RMARK is an R package that directly runs MARK and allows for easily reproducible and adjustable analyses.

A set of canddiate models under the POPAN framework were developed for estimating abundance and apparent surival of the 2023 release cohort.
Each candidate model represents a set of hypotheses regarding model parameters (e.g., capture probability varies over time or is constant).
For all models, the probability of entry into the population was manually fixed to 0.
We then explored models where:

1) super population was either constant or varied between facilities,
2) apparent survival was either constnat, varied over time, varied by facility, or varied over time and by facility,
3) capture probability was either constant, varied over time, or varied by facility.

For each model, MARK estimates model parameters based on the encounter histories.

To determine which model was most likely given the underlying data, MARK uses an information criteria approach that balances the goodness-of-fit with model complexity to rank the models. *SEE BURNHAM BOOKS for language*.

or

We used an information criteria approach to determine the model with the highest likelihood (i.e., balance of goodness of fit and model complexity) (Villella, Smith, and Lemarié 2004; Meador, Peterson, and Wisniewski 2011) *confirm these references*

We calculated the likelihood of each candidate model using Akaike’s Information Criterion (AIC) (Akaike 1973) modified for small sample sizes (AICc) (Sugiura 1978): 
$$𝐴𝐼𝐶𝑐=−2log(𝐿(θ̂))+2𝐾(𝐾+1)𝑛−𝐾−1$$

where 𝐿(θ̂) is the likelihood of the parameter estimates, given the data, K is the number of parameters, and n is the sample size. 
Normally, the best model is the one with the lowest AICc score and other models are considered competing if ΔAIC <2.0. 
However, top models for both species had issues estimating survival, especially on the last occasion. 
This is not uncommon in parameters that are modeled as fully time-dependent, especially when capture rates are relativley low. *reference?*
For purposes of estiamting survial/abundance, we decided to use the subset of the top model where time was remvoed as a factor for apparent survival (i.e, survival does not vary with time).  

1) Talk about field sampling
2) POPAN description and why
3) Data analysis
    1) POPAN
    2) PROGRAM MARK/RMARK
    3) Steps taken: 
        1) data cleaning
        2) rmark 
        3) etc. see internal documentation
4) other things to mention
    * Candidate models




I used a robust design, mark-recapture framework (Pollock 1982) to sample the Sycamore Lane and Payne Property sites in the Clinch River during the late summer/early fall from 2015 to 2017. Each year’s sampling represented a single primary period under the robust design framework. The population is assumed to be open to changes due to births, deaths, immigration, or emigration between primary periods (i.e., years). Each primary period consisted of two secondary sampling days as close to each other as possible (usually consecutive), when the population is assumed to be closed to changes due to births, deaths, immigration, or emigration between secondary periods (i.e., within each primary period). Each site was divided into 20-m wide transects oriented perpendicular to stream flow. Transects were divided into 1-m-wide lanes oriented parallel to flow to ensure full spatial coverage of the site. Each lane was sampled visually by snorkeling from the downstream to upstream end. In areas too shallow to snorkel, we used viewscopes or slowly walked through transect areas and visually inspected for mussels. Substrate was not excavated during sampling. Each individual mussel was identified to species, sexed (for dimorphic species), and measured (length). I also noted the collector of each mussel. Mussels already tagged had their tag number and tag color recorded. Any untagged mussels were tagged using Hallprint® glue-on shellfish tags and cyanoacrylate glue. After processing, mussels were returned to the location from which they were sampled.