# =============================================================================
# Script: 05_mark_analysis.py
#
# Purpose: Construct and run candidate model sets in MARK for each species  
#
# Inputs:
# - 04_mark_input.csv 
#
# Outputs:
# - Pipeline
#   - 05_mark_results.rds (R Object containing results of all analyses/model)  
# - Results
#   - MARK outputs (various files generated by MARk when running models/analysis)
#   - 05_mark_results.rds
# 
# Notes:
# Two versions of analysis were run in MARK:
# 1) Each species separately (1 sub analysis for each species)
# 2) All species together (1 assemblage level analysis)
# The assemblage level analysis had issues with model convergence, and, where it was able to 
#   estimate model parameters, those estimates were not substantially different than the
#   species level analyses. All subsequent steps use the species level analyses results.
# =============================================================================

# =============================================================================
# 1. Setup 
# =============================================================================

# -----------------------------------------------------------------------------
# Imports and Constants
# -----------------------------------------------------------------------------

library(RMark)
library(reticulate)
library(withr)
library(fs)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(writexl)
library(scales)

# -----------------------------------------------------------------------------
# Pulls path constants
# -----------------------------------------------------------------------------

global_paths = import("config.paths", convert = TRUE) 

# -----------------------------------------------------------------------------
# Load custom library
# -----------------------------------------------------------------------------

# Requires path constants to be loaded first
file_util = global_paths$file_util
util_file = path(global_paths$ROOT , "src", "util.r")
source(util_file)

# -----------------------------------------------------------------------------
# Paths and import/export directories
# -----------------------------------------------------------------------------

# Set directories
SCRIPT_NAME = '05_mark_analysis'
source_folder = path(global_paths$DATA_PIPELINE , '04_mark_input')
pipeline_folder = path(global_paths$DATA_PIPELINE , SCRIPT_NAME)
# Saving mark specific outputs (.inp, etc.) for review
mark_output_folder = path(global_paths$RESULTS, 'mark_output')
# Saving the R object that contains model results from RMARK analysis
mark_results_path = path(global_paths$RESULTS, 'objects', '05_mark_analysis')

# Make directories
dir_create(c(
  pipeline_folder,
  mark_output_folder,
  mark_results_path
  )
)

rm(current_time)

# =============================================================================
# 2. Load and transform mark input data
# =============================================================================

# -----------------------------------------------------------------------------
# Load data
# -----------------------------------------------------------------------------

source_file = path(source_folder, "04_mark_input.csv")
mark_input = read_csv(path(source_file), col_types=cols('ch' = col_character()))

# -----------------------------------------------------------------------------
# Transform data
# -----------------------------------------------------------------------------

# Assume dead observations were not observed for modeling purposes
mark_input$ch <- str_replace_all(mark_input$ch, 'D', '0') 

# E. fisheriana has only one tagged release
# Removed from all analyses)
mark_input = filter(mark_input,  Species != 'Elliptio fisheriana')

# L. cardium models did not successfully converge, likely due to low recapture rates (21/258) 
# Removed from all analyses
mark_input = filter(mark_input,  Species != 'Lampsilis cardium')

# Analyzing all data together adds an unnecessary potential factor to models (i.e., species)
# For ease of analysis, data was split and each species is analyzed separately in MARK, 
#  in addition to running analysis with all species combined
species_input <- split(mark_input, mark_input$Species)

# =============================================================================
# 3. Run POPAN analysis in MARK for each species separately
# =============================================================================

# -----------------------------------------------------------------------------
# Setup parameters, variables of interest, and other inputs
# -----------------------------------------------------------------------------

# Define group covariates 
groups = c("Facility")

# Define hypotheses to be tested for each model parameter
# Used further down to construct a candidate model set of all possible combinations
model_def = list(
  #phi
  Phi.dot=list(formula=~1),
  Phi.time = list(formula=~time),
  Phi.facility = list(formula=~Facility),
  Phi.facilityplustime = list(formula=~Facility + time), 
  #p
  p.dot=list(formula=~1),
  p.time=list(formula=~time),
  p.facility = list(formula=~Facility),
  #N
  N.dot=list(formula=~1),
  N.facility = list(formula=~Facility)
)

# -----------------------------------------------------------------------------
# Run candidate model set for each species separately 
# -----------------------------------------------------------------------------

# Saves results as a list where each item is a marklist object containing results for a single species
# Each marklist object then contains the results for the candidate models run for each species
# e.g.: results_list$`Alasmidonta varicosa`$Phi.facility.p.time.pent.0 
#   would contain results for the specified model and species
# To use most RMARK functions for extracting data from the results_list, 
#   you must typically call at the level above (i.e., model level)
# Create empty list for results:
results_list <- list()

# Constructs candidate model set of all possible combinations of model parameter hypotheses
#   based on model_def list above. All models are then run for each species directly in MARK 
#   and outputs saved   
# Run analysis for each species
# Mark output files (.inp, etc.) are saved in specified folder for review
species_list = names(species_input)
for (species in species_list) {
  species_df = species_input[[species]]
  popan_results = run_popan(species_df, groups, model_def, species, save_directory = mark_output_folder)
  results_list[[species]] = popan_results
}

# =============================================================================
# 4. Run POPAN analysis in MARK for the entire assemblage (species together)
# =============================================================================

# -----------------------------------------------------------------------------
# Setup parameters, variables of interest, and other inputs
# -----------------------------------------------------------------------------

# Define group covariates 
groups = c("Facility", "Species")

# Define hypotheses to be tested for each model parameter
# Used further down to construct a candidate model set of all possible combinations
model_def = list(
#phi
Phi.dot=list(formula=~1),
Phi.time = list(formula=~time),
Phi.facility = list(formula=~Facility),
Phi.species = list(formula=~Species),
#p
p.dot=list(formula=~1),
p.time=list(formula=~time),
p.facility = list(formula=~Facility),
p.species = list(formula=~Species),
#N
N.dot=list(formula=~1),
N.facility = list(formula=~Facility),
N.species = list(formula=~Species),
N.facilityplusspecies = list(formula=~Facility + Species)
)

# Constructs candidate model set of all possible combinations of model parameter hypotheses
#   based on model_def list above. All models are then run for each species directly in MARK 
#   and outputs saved   
# Run analysis for each species
# Mark output files (.inp, etc.) are saved in specified folder for review
assemblage_results = run_popan(mark_input, groups, model_def, "Assemblage", save_directory = mark_output_folder)
# Add assemblage analysis to results_list
results_list[["assemblage"]] = assemblage_results

# -----------------------------------------------------------------------------
# 5. Export of mark_models for further analysis
# -----------------------------------------------------------------------------

# Results_list contains results, inputs, model parameters, etc. for all models/analyses 
# The structure is too complicated to export cleanly for review in Excel/etc. 
# The entire R object is exported here for review of specific models/etc. in next step 

# -----------------------------------------------------------------------------
# Export to results folder 
# ----------------------------------------------------------------------------- 
mark_results_path = path(mark_results_path, '05_mark_results.rds')
saveRDS(results_list, mark_results_path, ascii = TRUE)

# -----------------------------------------------------------------------------
# Export for Pipeline 
# -----------------------------------------------------------------------------
mark_pipeline_path = path(pipeline_folder, '05_mark_results.rds')
saveRDS(results_list, mark_pipeline_path, ascii = TRUE)
